spring:
  application:
    name: portfolio-service
  profiles:
    active: dev
  # 업로드 파일 크기 제한
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true

logging:
  level:
    org.springframework.security.web.FilterChainProxy: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  prometheus:
    metrics:
      export:
        enabled: true



